from flask import Blueprint, jsonify, session
from flask_login import login_required, current_user
from models.database import db, Post, LinkedInAccount
from sqlalchemy import func
from datetime import datetime, timedelta

analytics_bp = Blueprint('analytics', __name__)

@analytics_bp.route('', methods=['GET'])
@login_required
def get_stats():
    active_account_id = session.get('active_account_id')

    query = Post.query.filter_by(user_id=current_user.id)
    if active_account_id:
        query = query.filter_by(linkedin_account_id=active_account_id)

    total_posts = query.count()
    published_posts = query.filter_by(status='Published').count()
    scheduled_posts = query.filter_by(status='Scheduled').count()
    failed_posts = query.filter_by(status='Failed').count()
    pending_approval = query.filter_by(status='Pending Approval').count()

    thirty_days_ago = datetime.utcnow() - timedelta(days=30)
    published_30d = query.filter(Post.status == 'Published', Post.created_at >= thirty_days_ago).count()

    success_rate = (published_posts / (published_posts + failed_posts) * 100) if (published_posts + failed_posts) > 0 else 0

    return jsonify({
        'total': total_posts,
        'published': published_posts,
        'published_30d': published_30d,
        'scheduled': scheduled_posts,
        'pending_approval': pending_approval,
        'failed': failed_posts,
        'success_rate': round(success_rate, 1)
    })


@analytics_bp.route('/activity', methods=['GET'])
@login_required
def get_activity():
    active_account_id = session.get('active_account_id')

    query = Post.query.filter_by(user_id=current_user.id)
    if active_account_id:
        query = query.filter_by(linkedin_account_id=active_account_id)

    recent_posts = query.order_by(Post.updated_at.desc()).limit(10).all()

    return jsonify([{
        'id': p.id,
        'topic': p.topic,
        'status': p.status,
        'updated_at': p.updated_at.isoformat() + 'Z',
        'error_message': p.error_message,
        'type': 'post'
    } for p in recent_posts])


@analytics_bp.route('/trends', methods=['GET'])
@login_required
def get_trends():
    """Returns 4 AI/ML trend headlines generated by Groq, cached every 6 hours."""
    import json, os
    from datetime import datetime
    from services.ai_generator import AIGenerator
    from config import Config

    cache_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'trends_cache.json')
    # Cache key = "YYYY-MM-DD-HH" where HH is floored to 6-hour block (0,6,12,18)
    now = datetime.utcnow()
    cache_slot = f"{now.strftime('%Y-%m-%d')}-{(now.hour // 6) * 6:02d}"

    try:
        if os.path.exists(cache_path):
            with open(cache_path, 'r', encoding='utf-8') as f:
                cache = json.load(f)
            if cache.get('slot') == cache_slot:
                return jsonify(cache.get('trends', []))
    except Exception:
        pass

    ai = AIGenerator(Config.GROQ_API_KEY)
    trends = ai.generate_trends()

    try:
        with open(cache_path, 'w', encoding='utf-8') as f:
            json.dump({'slot': cache_slot, 'trends': trends}, f, ensure_ascii=False)
    except Exception:
        pass

    return jsonify(trends)


@analytics_bp.route('/trends/refresh', methods=['POST'])
@login_required
def refresh_trends():
    """Force-regenerate trends, update the 6-hour cache slot."""
    import json, os
    from datetime import datetime
    from services.ai_generator import AIGenerator
    from config import Config

    ai = AIGenerator(Config.GROQ_API_KEY)
    trends = ai.generate_trends()

    now = datetime.utcnow()
    cache_slot = f"{now.strftime('%Y-%m-%d')}-{(now.hour // 6) * 6:02d}"
    cache_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'trends_cache.json')
    try:
        with open(cache_path, 'w', encoding='utf-8') as f:
            json.dump({'slot': cache_slot, 'trends': trends}, f, ensure_ascii=False)
    except Exception:
        pass

    return jsonify(trends)
